name: CI

on: push
  # push:
  #   branches:
  #     - main
  #     - master

jobs:

  build:
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: yarn.lock
      - name: Install Modules
        run: yarn install
      - name: Install app deps
        run: npx electron-builder install-app-deps
      - name: Build App
        run: yarn build:universal

  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Update release
        uses: johnwbyrd/update-release@v1
        with:
          token: ${{ secrets.github_token }}
          files: ./dist/mac-universal/On-Illegibility.app
