name: Pull Request
on:  
  push:
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    uses: ${{ format('StefKors/On-Illegibility/.github/workflows/build.yml@', {github.sha}) }}