name: Release Main
on:
  push:
    branches:
      - main
      - master
jobs:
  tag:
    uses: StefKors/On-Illegibility/.github/workflows/tag.yml@${{ github.ref }}
  build:
    needs: [tag]
    uses: StefKors/On-Illegibility/.github/workflows/build.yml@${{ github.ref }}