name: Release Main
on:
  push:
    branches:
      - main
      - master
jobs:
  tag:
    uses: ${{ format('StefKors/On-Illegibility/.github/workflows/tag.yml@', {github.sha}) }}
  build:
    needs: [tag]
    uses: ${{ format('StefKors/On-Illegibility/.github/workflows/build.yml@', {github.sha}) }}