name: Tag
on: 
  workflow_call:
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout  
        uses: actions/checkout@v2  
      - name:  'Automated Version Bump'
        uses:  'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag-prefix:  'v'